### ISSUE TITLE
Object target API suggestion

### ISSUE THREAD

**Issue by n-sidorov** [ZolutionSoftware/Rezolver#6]
Currently there is public generic extension `AsObjectTarget<T>(this T obj)` used to register constant(?) services into IoC.

Public static generic extensions are somewhat bad, because the will pop up for every single object that you are using in the project. In other words, in any place in the code you can invoke this extension method on any object, but it makes sense to invoke it only in IoC configuration.

It can be avoided with slight change in this method. Instead of generic extension, ITargetContainer extension can be implemented:

```
public static void RegisterAsObjectTarget<T>(this ITargetContainer container, T obj)
{
    ObjectTarget target = new ObjectTarget(obj);
    container.Register(target);
}
```

The result is more or less the same, but now every single object in project don't have an extension that cannot be used other then in IoC configuration.

**Comment by LordZoltan** [comment]
Hi there,

You're absolutely right - the `AsObjectTarget<T>` extension is there to simplify the registration of objects as services - however the usage is slightly different - it's there to enable quick *creation* of the `Rezolver.Targets.ObjectTarget` - which ultimately is how we implement objects as services.

In fact, there is already an extension for `ITargetContainer` which shortcuts creating and registering an `ObjectTarget` as a service: [public static void RegisterObject<T>(this ITargetContainer, T, ScopeBehaviour)](http://rezolver.co.uk/developers/api/Rezolver.ObjectTargetContainerExtensions.html#Rezolver_ObjectTargetContainerExtensions_RegisterObject__1_Rezolver_ITargetContainer___0_System_Type_Rezolver_ScopeBehaviour_).

So there's two uses here 

1. Creating a target in isolation (which doesn't require an `ITargetContainer`) 
2. Creating *and* registering a target at the same time

So, assuming 2 is fine as-is, the question is whether these public extensions over the core types (many can be found in [TargetCreationExtensions](http://rezolver.co.uk/developers/api/Rezolver.TargetCreationExtensions.html)) are bad.

I think I agree: they are.

Certainly, those extensions which pollute the member list of non-rezolver types (e.g. via a generic `T`, or on types such as `Delegate` etc); the ones which extend `ITarget` (e.g. [.Scoped](http://rezolver.co.uk/developers/api/Rezolver.TargetCreationExtensions.html#Rezolver_TargetCreationExtensions_Scoped_Rezolver_ITarget_) or [.Singleton](http://rezolver.co.uk/developers/api/Rezolver.TargetCreationExtensions.html#Rezolver_TargetCreationExtensions_Singleton_Rezolver_ITarget_)) are fine.

Being able to create targets in isolation is quite important for some other features, however - so we need a better way to do so.

## Proposal

I think the way to do this will be to have a `Target` static class in the `Rezolver` namespace with factory methods, so:

```
public static class Targets
{
  public static ObjectTarget ForObject<T>(T obj, ScopeBehaviour behaviour);

  public static DelegateTarget ForFactory(Delegate factory);
  
  // can also add the generic overloads for factory types for this /\ e.g:
  // public static DelegateTarget ForFactory<T1, T2, TResult>(Func<T1, T2, TResult> factory);

  ...
}
```
Which then makes target creation via these factory methods more expressive, too:

`var target = Target.ForObject("hello world");`

Or (using the generic overload mentioned in comments above):
`var target = Target.ForFactory((IService1 s1, IService2 s2) => return new Service3(s1, s2));`

In fact, we can also move a bunch of other static factories from elsewhere into this type, such as the [`ConstructorTarget.Auto`](http://rezolver.co.uk/developers/api/Rezolver.Targets.ConstructorTarget.html#Rezolver_Targets_ConstructorTarget_Auto_System_Type_Rezolver_IMemberBindingBehaviour_) overload, which could become `Target.ForType`.

Most of these factory methods for all the different targets are already there, just in different places (some are generated by T4 - e.g. for `DelegateTarget` and `ExpressionTarget`), so it won't be too difficult to relocate and rename them - obsoleting the existing stuff.

Thoughts?

**Comment by n-sidorov** [comment]
Yeah, if it is used to create targets outside of container then factory methods I think are a good way to do it. 'Target.For' syntax is very nice and readable in my opinion.

**Comment by LordZoltan** [comment]
This has now been removed from the code in the dev branch; and will be in the first prerelease version of 1.2.  

Also added are numerous static factory methods in the `Target` class for creating all the targets.

Issue will be closed when I do the next release :)
